general:
  cfApiEndpoint: "https://api.cf.eu10.hana.ondemand.com"
  cfOrg: "piper"
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryCreateSpace:
    cfCredentialsId: "cf_deploy"
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'cf_deploy'
  cloudFoundryDeleteSpace:
    cfCredentialsId: "cf_deploy"
