general:
  cfApiEndpoint: "https://api.cf.eu10.hana.ondemand.com"
  cfOrg: "CLOUDCI_cicddev"
  cfCredentialsId: "cfDeployFactory"
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'cfDeployFactory'

