general:
  cfApiEndpoint: "https://api.cf.eu10.hana.ondemand.com"
  cfOrg: "CLOUDCI_cicddev"
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryCreateSpace:
    cfCredentialsId: "cfDeployFactory"
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'cfDeployFactory'
  cloudFoundryDeleteSpace:
    cfCredentialsId: "cfDeployFactory"
